// Mocks generated by Mockito 5.4.6 from annotations
// in habits_flow/test/domain/use_cases/habit/add_habit_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:habits_flow/domain/entities/group_entity.dart' as _i8;
import 'package:habits_flow/domain/entities/habit_entity.dart' as _i5;
import 'package:habits_flow/domain/repos/group_repo.dart' as _i7;
import 'package:habits_flow/domain/repos/habit_repo.dart' as _i2;
import 'package:habits_flow/domain/responses/domain_response.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [HabitRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockHabitRepo extends _i1.Mock implements _i2.HabitRepo {
  MockHabitRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i4.DomainResponse<_i5.HabitEntity>> habitStream({
    required int? id,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#habitStream, [], {#id: id}),
            returnValue:
                _i3.Stream<_i4.DomainResponse<_i5.HabitEntity>>.empty(),
          )
          as _i3.Stream<_i4.DomainResponse<_i5.HabitEntity>>);

  @override
  _i3.Future<_i4.DomainResponse<_i5.HabitEntity>> createHabit({
    required String? title,
    required int? weight,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createHabit, [], {
              #title: title,
              #weight: weight,
            }),
            returnValue: _i3.Future<_i4.DomainResponse<_i5.HabitEntity>>.value(
              _i6.dummyValue<_i4.DomainResponse<_i5.HabitEntity>>(
                this,
                Invocation.method(#createHabit, [], {
                  #title: title,
                  #weight: weight,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.DomainResponse<_i5.HabitEntity>>);

  @override
  _i3.Future<_i4.DomainResponse<void>> deleteHabit({
    required String? habitId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteHabit, [], {#habitId: habitId}),
            returnValue: _i3.Future<_i4.DomainResponse<void>>.value(
              _i6.dummyValue<_i4.DomainResponse<void>>(
                this,
                Invocation.method(#deleteHabit, [], {#habitId: habitId}),
              ),
            ),
          )
          as _i3.Future<_i4.DomainResponse<void>>);

  @override
  _i3.Future<_i4.DomainResponse<void>> incHabitCount({
    required _i5.HabitEntity? habit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#incHabitCount, [], {#habit: habit}),
            returnValue: _i3.Future<_i4.DomainResponse<void>>.value(
              _i6.dummyValue<_i4.DomainResponse<void>>(
                this,
                Invocation.method(#incHabitCount, [], {#habit: habit}),
              ),
            ),
          )
          as _i3.Future<_i4.DomainResponse<void>>);

  @override
  _i3.Future<_i4.DomainResponse<void>> resetHabitCount({
    required _i5.HabitEntity? habit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#resetHabitCount, [], {#habit: habit}),
            returnValue: _i3.Future<_i4.DomainResponse<void>>.value(
              _i6.dummyValue<_i4.DomainResponse<void>>(
                this,
                Invocation.method(#resetHabitCount, [], {#habit: habit}),
              ),
            ),
          )
          as _i3.Future<_i4.DomainResponse<void>>);
}

/// A class which mocks [GroupRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockGroupRepo extends _i1.Mock implements _i7.GroupRepo {
  MockGroupRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i8.GroupEntity> groupStream({required String? groupId}) =>
      (super.noSuchMethod(
            Invocation.method(#groupStream, [], {#groupId: groupId}),
            returnValue: _i3.Stream<_i8.GroupEntity>.empty(),
          )
          as _i3.Stream<_i8.GroupEntity>);

  @override
  _i3.Future<_i4.DomainResponse<_i8.GroupEntity>> createGroup({
    required String? title,
    required int? weight,
    required String? colorHex,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createGroup, [], {
              #title: title,
              #weight: weight,
              #colorHex: colorHex,
            }),
            returnValue: _i3.Future<_i4.DomainResponse<_i8.GroupEntity>>.value(
              _i6.dummyValue<_i4.DomainResponse<_i8.GroupEntity>>(
                this,
                Invocation.method(#createGroup, [], {
                  #title: title,
                  #weight: weight,
                  #colorHex: colorHex,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.DomainResponse<_i8.GroupEntity>>);

  @override
  _i3.Future<_i4.DomainResponse<void>> deleteGroup({
    required String? groupId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteGroup, [], {#groupId: groupId}),
            returnValue: _i3.Future<_i4.DomainResponse<void>>.value(
              _i6.dummyValue<_i4.DomainResponse<void>>(
                this,
                Invocation.method(#deleteGroup, [], {#groupId: groupId}),
              ),
            ),
          )
          as _i3.Future<_i4.DomainResponse<void>>);

  @override
  _i3.Future<_i4.DomainResponse<_i8.GroupEntity>> addHabitToGroup({
    required String? groupId,
    required _i5.HabitEntity? habit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addHabitToGroup, [], {
              #groupId: groupId,
              #habit: habit,
            }),
            returnValue: _i3.Future<_i4.DomainResponse<_i8.GroupEntity>>.value(
              _i6.dummyValue<_i4.DomainResponse<_i8.GroupEntity>>(
                this,
                Invocation.method(#addHabitToGroup, [], {
                  #groupId: groupId,
                  #habit: habit,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.DomainResponse<_i8.GroupEntity>>);

  @override
  _i3.Stream<List<_i8.GroupEntity>> getGroupsListStream() =>
      (super.noSuchMethod(
            Invocation.method(#getGroupsListStream, []),
            returnValue: _i3.Stream<List<_i8.GroupEntity>>.empty(),
          )
          as _i3.Stream<List<_i8.GroupEntity>>);

  @override
  _i3.Future<_i4.DomainResponse<void>> removeLastDummy() =>
      (super.noSuchMethod(
            Invocation.method(#removeLastDummy, []),
            returnValue: _i3.Future<_i4.DomainResponse<void>>.value(
              _i6.dummyValue<_i4.DomainResponse<void>>(
                this,
                Invocation.method(#removeLastDummy, []),
              ),
            ),
          )
          as _i3.Future<_i4.DomainResponse<void>>);

  @override
  _i3.Future<_i4.DomainResponse<void>> addDummyHabitToFirstGroup() =>
      (super.noSuchMethod(
            Invocation.method(#addDummyHabitToFirstGroup, []),
            returnValue: _i3.Future<_i4.DomainResponse<void>>.value(
              _i6.dummyValue<_i4.DomainResponse<void>>(
                this,
                Invocation.method(#addDummyHabitToFirstGroup, []),
              ),
            ),
          )
          as _i3.Future<_i4.DomainResponse<void>>);

  @override
  _i3.Future<_i4.DomainResponse<void>> generateDummyGroupName({
    required String? groupId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#generateDummyGroupName, [], {#groupId: groupId}),
            returnValue: _i3.Future<_i4.DomainResponse<void>>.value(
              _i6.dummyValue<_i4.DomainResponse<void>>(
                this,
                Invocation.method(#generateDummyGroupName, [], {
                  #groupId: groupId,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.DomainResponse<void>>);
}
